"""initial

Revision ID: ab6294541034
Revises: 
Create Date: 2026-02-27 23:00:39.474535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6294541034'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_reasoning', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('occurred_at', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_events_source_source_id')
    )
    op.create_table('knowledge_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('detected_at', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_events',
    sa.Column('knowledge_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_id', 'event_id')
    )
    op.create_table('knowledge_merges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('primary_id', sa.String(length=36), nullable=True),
    sa.Column('merged_id', sa.String(length=36), nullable=True),
    sa.Column('merge_score', sa.Float(), nullable=True),
    sa.Column('merged_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['primary_id'], ['knowledge_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('checked_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_checks')
    op.drop_table('knowledge_merges')
    op.drop_table('knowledge_events')
    op.drop_table('knowledge_objects')
    op.drop_table('events')
    op.drop_table('chat_messages')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('integrations')
    op.drop_table('teams')
    # ### end Alembic commands ###
